print("Hello")
print("My name is Irene Elsa John")
print("I am 13 y/o")
print("I am studying in class 9th")
print("In Mar Dionysious Senior Secondary School ")
print("My brothers name is Iwin John Prakash")
print("My mothers name is Sine Simon")
print("My fathers name is Prakash John")
print("My brother is stuyding in class 4th")
print("My mother is a ICICI prodential staff")
print("My father is a civil worker")
print("My hobbies are stamp collection and coin collection")
print("THANK YOU")
